### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hassankhan** [react-native-contrib/rsx#2]
### This is just a brain-dump of all the things that are yet to be done - these should ideally be spun off into their own repo's issues whenever I get the time
- [ ] Consider creating `rsx-local` and only using `rsx` with `rsx-new` to create a project
- [ ] Add code docblocks
## rsx-docs
- [ ] Add installable commands section
## rsx-generator-android
- [ ] Fix up generator project structure as per YeomanGenGen
- [ ] Have an upgrade path
- [ ] Unpublish and re-release as `generator-rsx-android`
- [ ] Tests
## rsx-generator-base
- [ ] Fix up generator project structure as per YeomanGenGen
- [ ] Have an upgrade path
- [ ] Unpublish and re-release as `generator-rsx-base`
- [ ] Tests
## rsx-generator-ios
- [ ] Fix up generator project structure as per YeomanGenGen
- [ ] Have an upgrade path
- [ ] Unpublish and re-release as `generator-rsx-ios`
- [ ] Tests
## rsx-resources
- [ ] Should fail if `process.env.RN_PROJECT_ROOT` is not set
- [ ] Docs

http://maximilianschmitt.me/posts/compile-es6-command-line-apps/

``` bash
rsx new [project] --platforms=[platforms]

rsx platforms ls
rsx platforms add [platforms]
rsx platforms rm [platforms]

rsx plugins ls
rsx plugins add [plugins]
rsx plugins rm [plugins]

rsx resources [resource]

rsx run [platform] --target=[device|simulator]
rsx status

rsx upgrade --dependencies --platforms --plugins
```
